# Based on https://github.com/confluentinc/cp-docker-images/blob/master/examples/cp-all-in-one/docker-compose.yml

version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    ports:
      - 127.0.0.1:2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper
    ports:
      - 127.0.0.1:9093:9093
      - 127.0.0.1:9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'

      # We need zookeeper to advertise two different urls since the broker has to be reachable
      # from two different environments (once from inside the docker network and once from the host)
      # However it is neither possible to advertise two listeners but only configure one via KAFKA_LISTENERS
      # nor is it possible to advertise two listeners with the same protocol but different ports and hostnames since
      # they are still considered to have the same name.
      # We can do nothing about the former case but we can trick kafka with a custom protocol in the latter case.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://127.0.0.1:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  schema-registry:
    image: confluentinc/cp-schema-registry:6.1.1
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 127.0.0.1:8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_LISTENERS: 'http://127.0.0.1:8081'

  kafka-rest:
    image: confluentinc/cp-kafka-rest:6.1.1
    depends_on:
      - kafka
      - schema-registry
    ports:
      - 127.0.0.1:8082:8082
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka:9092'
      KAFKA_REST_HOST_NAME: 'kafka-rest'
      KAFKA_REST_LISTENERS: 'http://127.0.0.1:8082'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
